# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateField()),
                ('closed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Case')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('facility_time', models.BooleanField(verbose_name=b'Pays into facility time pot')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_names', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message=b'Phonenumber must be 11 digits long and start with 0', regex=b'0[0-9]{10}')])),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message=b'Phonenumber must be 11 digits long and start with 0', regex=b'0[0-9]{10}')])),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Caseworker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caseworkclub.Person')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Association')),
            ],
            bases=('caseworkclub.person',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='caseworkclub.Person')),
                ('membership_number', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message=b'NUT Membership Numbers have a capital letter and five digits.', regex=b'[A-Z]\\d{5}')])),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Association')),
            ],
            bases=('caseworkclub.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='workplace',
            field=models.ManyToManyField(through='caseworkclub.Job', to='caseworkclub.Workplace'),
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Workplace'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Person'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='notetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.NoteType'),
        ),
        migrations.AddField(
            model_name='case',
            name='caseworktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.CaseworkType'),
        ),
        migrations.AddField(
            model_name='case',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Workplace'),
        ),
        migrations.AddField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Caseworker'),
        ),
        migrations.AddField(
            model_name='case',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Member'),
        ),
    ]
