# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseworktype',
        ),
        migrations.AddField(
            model_name='case',
            name='caseworktype',
            field=models.ManyToManyField(to='caseworkclub.CaseworkType'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='typename',
            field=models.CharField(max_length=2),
        ),
    ]
