# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0002_auto_20170212_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='caseworktype',
            new_name='caseworktypes',
        ),
    ]
