# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0002_auto_20170120_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
