# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0003_auto_20170212_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settime', models.DateTimeField(default=django.utils.timezone.now)),
                ('completedtime', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Case')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Person')),
                ('tasktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.NoteType')),
            ],
        ),
    ]
