# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0003_auto_20170224_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='opened',
            field=models.DateField(auto_now_add=True),
        ),
    ]
