# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0004_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='association',
        ),
        migrations.AddField(
            model_name='case',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Association'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='completedtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
