# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0004_caseworker_employer_managementcontact_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Workplace',
        ),
        migrations.AddField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Caseworker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='workplace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Workplace'),
            preserve_default=False,
        ),
    ]
