# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0005_auto_20170212_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='id',
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
