# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0008_auto_20170121_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='number',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_number',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
