# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0009_auto_20170121_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworker',
            name='first_names',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseworker',
            name='surname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
