# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 00:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0010_auto_20170121_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_names', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_names', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ManagementContact',
        ),
        migrations.AddField(
            model_name='caseworker',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='caseworker',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='caseworker',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='workplace',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='first_names',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='manager',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Workplace'),
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Employer'),
        ),
    ]
