# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0011_auto_20170122_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Association'),
            preserve_default=False,
        ),
    ]
