# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0012_member_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='facility_time',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
