# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0013_employer_facility_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='facility_time',
            field=models.BooleanField(verbose_name='Pays into facility time pot'),
        ),
    ]
