# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 02:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0015_auto_20170122_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_names', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phonenumber must be 11 digits long and start with 0', regex='0[0-9]{10}')])),
            ],
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='caseworker',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.AddField(
            model_name='emailnote',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Person'),
        ),
        migrations.AddField(
            model_name='caseworker',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caseworkclub.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caseworkclub.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caseworkclub.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='caseworkclub.Person'),
            preserve_default=False,
        ),
    ]
