# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0017_auto_20170122_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='job',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
