# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0018_manager_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseworktype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='caseworktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.CaseworkType'),
        ),
    ]
