# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0019_auto_20170123_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseworktype',
            old_name='caseworktype',
            new_name='typename',
        ),
    ]
