# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0020_auto_20170123_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Case')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.Person')),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailnote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='emailnote',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='meetingnote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='phonenote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='phonenote',
            name='contact',
        ),
        migrations.DeleteModel(
            name='EmailNote',
        ),
        migrations.DeleteModel(
            name='MeetingNote',
        ),
        migrations.DeleteModel(
            name='PhoneNote',
        ),
    ]
