# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0022_auto_20170126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenote',
            name='casetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caseworkclub.NoteType'),
            preserve_default=False,
        ),
    ]
