# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseworkclub', '0023_casenote_casetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casenote',
            old_name='casetype',
            new_name='notetype',
        ),
    ]
